# Simple Agent System Configuration
system:
  name: "Simple Agent System"
  version: "1.0.0"
  host: "127.0.0.1"
  port: 8080

# Default agents to create on startup
agents:
  - name: "Assistant"
    capabilities: ["chat", "analysis"]
    auto_start: true
  
  - name: "Analyzer" 
    capabilities: ["analysis", "data_processing"]
    auto_start: true

# Available functions
functions:
  chat:
    description: "Basic chat functionality"
    parameters:
      - name: "message"
        type: "string"
        required: true
        description: "Message to send to the agent"
  
  analyze:
    description: "Text analysis functionality"
    parameters:
      - name: "text"
        type: "string"
        required: true
        description: "Text to analyze"
  
  echo:
    description: "Echo function for testing"
    parameters:
      - name: "data"
        type: "any"
        required: false
        description: "Data to echo back"
  
  status:
    description: "Agent status information"
    parameters: []
