server:
  port: 8080
  host: 127.0.0.1
  idle_timeout: 300
  allow_public_access: false
  allow_internet_access: false
logging:
  level: INFO
  file: ""
  access_log: false
  quiet_mode: false
  show_request_details: true
auth:
  enabled: true
  require_api_key: false
  api_key_header: X-API-Key
  api_keys:
    []
  rate_limit:
    enabled: true
    max_requests: 100
    window_size: 60
  cors:
    enabled: true
    allow_credentials: false
    max_age: 86400
    allowed_origins:
      - "*"
    allowed_methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - HEAD
      - PATCH
    allowed_headers:
      - Content-Type
      - Authorization
      - X-Requested-With
      - Accept
      - Origin
search:
  enabled: false
  searxng_url: http://localhost:4000
  timeout: 30
  max_results: 20
  default_engine: ""
  api_key: ""
  enable_safe_search: true
  default_format: json
  default_language: en
  default_category: general
database:
  qdrant:
    enabled: false
    host: localhost
    port: 6333
    collection_name: documents
    default_embedding_model: text-embedding-3-small
    timeout: 30
    api_key: ""
    max_connections: 10
    connection_timeout: 5
    embedding_batch_size: 5
inference_engines:
  - name: llama-cpu
    library_path: D:\Works\Genta\codes\kolosal-agent\build\kolosal-server\Debug/llama-cpu.dll
    version: 1.0.0
    description: CPU inference engine
    load_on_startup: true
default_inference_engine: llama-cpu
features:
  health_check: true
  metrics: false