server:
  port: 8081
  host: 127.0.0.1
  idle_timeout: 300
  allow_public_access: false
  allow_internet_access: false
logging:
  level: INFO
  file: ""
  access_log: false
  quiet_mode: false
  show_request_details: true
auth:
  enabled: false
  require_api_key: false
  api_key_header: X-API-Key
  api_keys:
    []
  rate_limit:
    enabled: true
    max_requests: 100
    window_size: 60
  cors:
    enabled: true
    allow_credentials: false
    max_age: 86400
    allowed_origins:
      - "*"
    allowed_methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - HEAD
      - PATCH
    allowed_headers:
      - Content-Type
      - Authorization
      - X-Requested-With
      - Accept
      - Origin
search:
  enabled: true
  searxng_url: https://searx.stream/
  timeout: 30
  max_results: 20
  default_engine: ""
  api_key: ""
  enable_safe_search: true
  default_format: json
  default_language: en
  default_category: general
database:
  vector_database: qdrant
  retrieval_embedding_model: "all-MiniLM-L6-v2-bf16-q4_k"
  qdrant:
    enabled: true
    host: localhost
    port: 6333
    collection_name: documents
    default_embedding_model: "all-MiniLM-L6-v2-bf16-q4_k"
    timeout: 30
    api_key: ""
    max_connections: 10
    connection_timeout: 5
    embedding_batch_size: 5
  faiss:
    index_type: Flat
    index_path: D:\Works\Genta\codes\kolosal-agent\data\faiss_index
    dimensions: 1536
    normalize_vectors: true
    nlist: 100
    nprobe: 10
    use_gpu: false
    gpu_device: 0
    metric_type: IP
models:
  - id: qwen2.5-0.5b
    path: D:\Works\Genta\codes\kolosal-agent\models\qwen2.5-0.5b-instruct-q4_k_m.gguf
    type: llm
    load_immediately: true
    main_gpu_id: 0
    inference_engine: llama-cpu
    load_params:
      n_ctx: 2048
      n_keep: 1024
      use_mmap: true
      use_mlock: false
      n_parallel: 1
      cont_batching: true
      warmup: false
      n_gpu_layers: 0
      n_batch: 2048
      n_ubatch: 512
  - id: all-MiniLM-L6-v2-bf16-q4_k
    path: D:\Works\Genta\codes\kolosal-agent\models\all-MiniLM-L6-v2-bf16-q4_k.gguf
    type: embedding
    load_immediately: true
    main_gpu_id: 0
    inference_engine: llama-cpu
    load_params:
      n_ctx: 512
      use_mmap: true
      use_mlock: false
      embedding_only: true
inference_engines:
  - name: llama-cpu
    library_path: D:\Works\Genta\codes\kolosal-agent\build\Debug\llama-cpu.dll
    version: 1.0.0
    description: CPU-based inference engine for LLaMA models
    load_on_startup: true
default_inference_engine: llama-cpu
features:
  health_check: true
  metrics: true