# Deep Research Agent Configuration
# Configuration file for the Deep Research demonstration

# Server configuration
server:
  url: "http://localhost:8080"
  timeout: 30
  max_retries: 3
  enable_https: false

# Research configuration defaults
research:
  methodology: "systematic"
  depth_level: "comprehensive"
  max_sources: 30
  max_web_results: 20
  relevance_threshold: 0.75
  include_academic: true
  include_news: true
  include_documents: true
  output_format: "comprehensive_report"
  language: "en"

# Agent configuration
agent:
  name: "DeepResearchAgent"
  role: "RESEARCHER"
  specializations:
    - "WEB_RESEARCH"
    - "DOCUMENT_ANALYSIS"
    - "REASONING"
  capabilities:
    - "research_planning"
    - "source_analysis"
    - "information_synthesis"
    - "fact_verification"
    - "report_generation"

# Workflow configuration
workflows:
  comprehensive_research:
    max_execution_time: 1800  # 30 minutes
    timeout_per_step: 600     # 10 minutes
    max_retries: 2
    continue_on_error: true
  
  quick_research:
    max_execution_time: 600   # 10 minutes
    timeout_per_step: 300     # 5 minutes
    max_retries: 1
    continue_on_error: true
  
  academic_research:
    max_execution_time: 2400  # 40 minutes
    timeout_per_step: 900     # 15 minutes
    max_retries: 2
    continue_on_error: false

# Logging configuration
logging:
  level: "INFO"
  enable_console: true
  enable_file: false
  max_log_size_mb: 10

# Demo configuration
demo:
  show_progress: true
  detailed_output: true
  save_reports: false
  interactive_mode: true
