# Workflow Con  simple_research:
    name: "Simple Research Workflow"
    description: "Basic research workflow using a single agent with specific LLM"
    type: "sequential"
    max_execution_time_ms: 180000
    allow_partial_failure: false
    steps:
      - id: "research_step"
        agent_name: "Researcher"  # References agent from agent.yaml
        llm_model: "gemma3-1b"    # Specific LLM model from config.yaml
        function_name: "research"
        parameters:
          - "query"
          - "depth"
        timeout_ms: 120000
        optional: falseolosal Agent System
# This file defines workflows that use agents from agent.yaml with specific LLM models

# Default workflow settings
settings:
  max_concurrent_workflows: 10
  default_timeout_ms: 300000
  cleanup_completed_after_hours: 24
  enable_workflow_logging: true
  log_level: "info"

# Workflow definitions - each workflow pairs agents with specific LLM models
workflows:
  # Simple Research Workflow
  - id: "simple_research"
    name: "Simple Research Workflow"
    description: "Basic research workflow using a single agent with specific LLM"
    type: "sequential"
    max_execution_time_ms: 180000
    allow_partial_failure: false
    steps:
      - id: "research_step"
        agent_name: "Researcher"  # References agent from agent.yaml
        llm_model: "gemma3-1b"    # Specific LLM model from config.yaml
        function_name: "research"
        parameters:
          - "query"
          - "depth"
        timeout_ms: 120000
        optional: false

  # Analysis Workflow with Agent-LLM pairs
  - id: "analysis_workflow"
    name: "Text Analysis Workflow"
    description: "Multi-step analysis using different agents with specific LLMs"
    type: "sequential"
    max_execution_time_ms: 240000
    allow_partial_failure: false
    steps:
      - id: "initial_analysis"
        agent_name: "Analyzer"
        llm_model: "gemma3-1b"
        function_name: "analyze"
        parameters:
          - "text"
          - "analysis_type"
        timeout_ms: 60000
        optional: false
      
      - id: "detailed_analysis"
        agent_name: "Analyzer"
        llm_model: "gemma3-1b"
        function_name: "analyze"
        parameters:
          - "text"
          - "analysis_type"
          - "context"
        timeout_ms: 90000
        optional: false
        dependencies: ["initial_analysis"]

  # Conversational Workflow
  - id: "conversation_workflow"
    name: "Multi-Agent Conversation"
    description: "Workflow where different agents converse using specific LLMs"
    type: "sequential"
    max_execution_time_ms: 300000
    allow_partial_failure: true
    steps:
      - id: "assistant_response"
        agent_name: "Assistant"
        llm_model: "gemma3-1b"
        function_name: "chat"
        parameters:
          - "message"
          - "model"
        timeout_ms: 30000
        optional: false
      
      - id: "analysis_feedback"
        agent_name: "Analyzer"
        llm_model: "gemma3-1b"
        function_name: "analyze"
        parameters:
          - "text"
          - "analysis_type"
        timeout_ms: 45000
        optional: true
        dependencies: ["assistant_response"]

  # Research and Analysis Pipeline
  - id: "research_analysis_pipeline"
    name: "Research and Analysis Pipeline"
    description: "Complete research pipeline with multiple agents and LLM pairing"
    type: "sequential"
    max_execution_time_ms: 600000
    allow_partial_failure: false
    steps:
      - id: "research_phase"
        agent_name: "Researcher"
        llm_model: "gemma3-1b"
        function_name: "research"
        parameters:
          - "query"
          - "depth"
        timeout_ms: 180000
        optional: false
      
      - id: "analysis_phase"
        agent_name: "Analyzer"
        llm_model: "gemma3-1b"
        function_name: "analyze"
        parameters:
          - "text"
          - "analysis_type"
        timeout_ms: 120000
        optional: false
        dependencies: ["research_phase"]
      
      - id: "final_summary"
        agent_name: "Assistant"
        llm_model: "gemma3-1b"
        function_name: "chat"
        parameters:
          - "message"
          - "model"
        timeout_ms: 60000
        optional: false
        dependencies: ["analysis_phase"]

  # Parallel Processing Workflow
  - id: "parallel_analysis"
    name: "Parallel Analysis Workflow"
    description: "Process multiple aspects in parallel using different agent-LLM pairs"
    type: "parallel"
    max_execution_time_ms: 180000
    allow_partial_failure: true
    steps:
      - id: "sentiment_analysis"
        agent_name: "Analyzer"
        llm_model: "gemma3-1b"
        function_name: "analyze"
        parameters:
          - "text"
          - "analysis_type"
        timeout_ms: 60000
        optional: false
      
      - id: "keyword_extraction"
        agent_name: "Analyzer"
        llm_model: "gemma3-1b"
        function_name: "analyze"
        parameters:
          - "text"
          - "analysis_type"
        timeout_ms: 60000
        optional: false
      
      - id: "summary_generation"
        agent_name: "Assistant"
        llm_model: "gemma3-1b"
        function_name: "chat"
        parameters:
          - "message"
          - "model"
        timeout_ms: 45000
        optional: false

  # Deep Research Workflow - Comprehensive multi-step research with iterative refinement
  - id: "deep_research_workflow"
    name: "Deep Research Workflow"
    description: "Comprehensive multi-step research workflow with iterative depth and cross-validation"
    type: "sequential"
    max_execution_time_ms: 1800000  # 30 minutes
    allow_partial_failure: false
    steps:
      # Phase 1: Initial Research Planning
      - id: "research_planning"
        agent_name: "Researcher"
        llm_model: "gemma3-1b"
        function_name: "plan_research"
        parameters:
          - "query"
          - "research_scope"
          - "depth_level"
        timeout_ms: 120000
        optional: false
      
      # Phase 2: Primary Internet Research
      - id: "primary_research"
        agent_name: "Researcher"
        llm_model: "gemma3-1b"
        function_name: "internet_search"
        parameters:
          - "query"
          - "results"
          - "language"
        timeout_ms: 180000
        optional: false
        dependencies: ["research_planning"]
      
      # Phase 3: Knowledge Base Search
      - id: "knowledge_base_search"
        agent_name: "RetrievalAgent"
        llm_model: "gemma3-1b"
        function_name: "search_documents"
        parameters:
          - "query"
          - "limit"
          - "threshold"
        timeout_ms: 60000
        optional: true
        dependencies: ["primary_research"]
      
      # Phase 4: Research Synthesis and Gap Analysis
      - id: "research_synthesis"
        agent_name: "Analyzer"
        llm_model: "gemma3-1b"
        function_name: "synthesize_research"
        parameters:
          - "primary_data"
          - "knowledge_base_data"
          - "synthesis_type"
        timeout_ms: 180000
        optional: false
        dependencies: ["primary_research", "knowledge_base_search"]
      
      # Phase 5: Secondary Research (based on gaps identified)
      - id: "secondary_research"
        agent_name: "Researcher"
        llm_model: "gemma3-1b"
        function_name: "targeted_research"
        parameters:
          - "research_gaps"
          - "search_terms"
          - "sources"
        timeout_ms: 240000
        optional: false
        dependencies: ["research_synthesis"]
      
      # Phase 6: Cross-validation and Fact-checking
      - id: "fact_verification"
        agent_name: "Researcher"
        llm_model: "gemma3-1b"
        function_name: "verify_facts"
        parameters:
          - "findings"
          - "sources"
          - "verification_depth"
        timeout_ms: 180000
        optional: false
        dependencies: ["secondary_research"]
      
      # Phase 7: Final Analysis and Insights
      - id: "deep_analysis"
        agent_name: "Analyzer"
        llm_model: "gemma3-1b"
        function_name: "analyze"
        parameters:
          - "text"
          - "analysis_type"
          - "context"
        timeout_ms: 180000
        optional: false
        dependencies: ["fact_verification"]
      
      # Phase 8: Report Generation with Citations
      - id: "report_generation"
        agent_name: "Assistant"
        llm_model: "gemma3-1b"
        function_name: "generate_research_report"
        parameters:
          - "research_data"
          - "analysis_results"
          - "report_format"
          - "include_citations"
        timeout_ms: 120000
        optional: false
        dependencies: ["deep_analysis"]
      
      # Phase 9: Knowledge Base Update (store findings for future use)
      - id: "knowledge_update"
        agent_name: "RetrievalAgent"
        llm_model: "gemma3-1b"
        function_name: "add_document"
        parameters:
          - "content"
          - "title"
          - "metadata"
        timeout_ms: 60000
        optional: true
        dependencies: ["report_generation"]

  # Conditional Workflow Example
  - id: "conditional_processing"
    name: "Conditional Processing Workflow"
    description: "Workflow with conditional steps based on previous results"
    type: "conditional"
    max_execution_time_ms: 240000
    allow_partial_failure: false
    steps:
      - id: "initial_check"
        agent_name: "Assistant"
        llm_model: "gemma3-1b"
        function_name: "chat"
        parameters:
          - "message"
          - "model"
        timeout_ms: 30000
        optional: false
      
      - id: "detailed_processing"
        agent_name: "Analyzer"
        llm_model: "gemma3-1b"
        function_name: "analyze"
        parameters:
          - "text"
          - "analysis_type"
        timeout_ms: 90000
        optional: false
        condition:
          type: "contains"
          field: "steps.initial_check.result"
          value: "needs processing"
        dependencies: ["initial_check"]

# Agent-LLM Model Mappings
# This section defines valid pairings of agents with LLM models
agent_llm_mappings:
  Assistant:
    default_model: "gemma3-1b"
    supported_models: ["gemma3-1b"]
    
  Analyzer:
    default_model: "gemma3-1b"
    supported_models: ["gemma3-1b"]
    
  Researcher:
    default_model: "gemma3-1b"
    supported_models: ["gemma3-1b"]
    
  RetrievalAgent:
    default_model: "gemma3-1b"
    supported_models: ["gemma3-1b"]
    
  DeepResearcher:
    default_model: "gemma3-1b"
    supported_models: ["gemma3-1b"]

# Workflow execution settings
execution:
  # Maximum number of concurrent workflow executions
  max_concurrent_executions: 5
  
  # Default step timeout if not specified
  default_step_timeout_ms: 60000
  
  # Retry settings for failed steps
  retry:
    enabled: true
    max_attempts: 3
    backoff_factor: 2.0
    initial_delay_ms: 1000
  
  # Resource limits
  resources:
    max_memory_per_workflow: "1GB"
    max_cpu_usage_percent: 80
  
  # Monitoring and logging
  monitoring:
    enable_step_metrics: true
    enable_performance_tracking: true
    log_step_inputs: false  # Set to true for debugging
    log_step_outputs: false # Set to true for debugging

# Template workflows for common patterns
templates:
  basic_chat:
    description: "Simple chat interaction with an agent"
    parameters:
      - name: "agent_name"
        type: "string"
        required: true
        description: "Name of the agent to use"
      - name: "message"
        type: "string"
        required: true
        description: "Message to send to agent"
      - name: "model"
        type: "string"
        required: false
        default: "gemma3-1b"
        description: "LLM model to use"
  
  basic_analysis:
    description: "Simple text analysis workflow"
    parameters:
      - name: "text"
        type: "string"
        required: true
        description: "Text to analyze"
      - name: "analysis_type"
        type: "string"
        required: false
        default: "summary"
        description: "Type of analysis to perform"
  
  deep_research:
    description: "Comprehensive multi-phase research workflow"
    parameters:
      - name: "query"
        type: "string"
        required: true
        description: "Primary research question or topic"
      - name: "research_scope"
        type: "string"
        required: false
        default: "comprehensive"
        description: "Scope of research (narrow, broad, comprehensive)"
      - name: "depth_level"
        type: "string"
        required: false
        default: "advanced"
        description: "Research depth level (basic, intermediate, advanced, expert)"
      - name: "report_format"
        type: "string"
        required: false
        default: "detailed"
        description: "Format of the final report (academic, business, summary, detailed)"
      - name: "include_citations"
        type: "boolean"
        required: false
        default: true
        description: "Whether to include source citations in the report"
