# Kolosal Server Configuration Template
# This file provides optimal configuration for the Kolosal Server
# when used with the Kolosal Agent System

server:
  # Network configuration
  host: "127.0.0.1"
  port: 8081
  
  # Security settings - configure per deployment
  cors_enabled: false
  cors_origins: []
  
  # Performance settings
  max_connections: 100
  request_timeout: 60
  max_request_size: "10MB"
  
  # Logging
  log_level: "INFO"
  log_file: "kolosal_server.log"
  access_log: true

# Model configuration
models:
  # Default models directory
  models_path: "./models"
  
  # Model loading settings
  preload_timeout: 120
  model_cache_size: "1GB"
  
  # LLM Models
  llm_models:
    - name: "qwen2.5-0.5b"
      file: "qwen2.5-0.5b-instruct-q4_k_m.gguf"  # Using available model
      context_size: 2048
      gpu_layers: 0  # Adjust based on available GPU
      threads: 4
      preload: true
      
  # Embedding Models
  embedding_models:
    - name: "all-MiniLM-L6-v2-bf16-q4_k"
      file: "all-MiniLM-L6-v2-bf16-q4_k.gguf"
      embedding_size: 384
      preload: true
      threads: 2

# Retrieval system configuration
retrieval:
  # Vector database settings
  vector_db:
    type: "faiss"  # or "chroma" if available
    index_type: "HNSW"
    metric: "cosine"
    
  # Document processing
  chunking:
    chunk_size: 512
    chunk_overlap: 50
    strategy: "recursive"
    
  # Search settings
  search:
    default_limit: 10
    max_limit: 100
    similarity_threshold: 0.7

# Internet search configuration (optional)
internet_search:
  enabled: true   # Set to true to enable web search
  provider: "duckduckgo"  # or "google", "bing"
  max_results: 20
  timeout: 30
  
  # Rate limiting
  rate_limit:
    requests_per_minute: 60
    requests_per_hour: 1000

# Resource management
resources:
  # Memory limits
  max_memory_usage: "1.5GB"
  memory_cleanup_threshold: 0.8
  
  # CPU usage
  max_cpu_percent: 80
  cpu_monitoring: true
  
  # Disk space
  min_disk_space_gb: 2
  temp_dir_cleanup: true

# Health monitoring
health:
  # Health check endpoint
  endpoint: "/health"
  
  # Monitoring intervals
  model_check_interval: 30
  resource_check_interval: 10
  
  # Alerts
  alerts:
    high_memory_threshold: 0.9
    high_cpu_threshold: 0.9
    model_failure_retry: 3

# Error handling
error_handling:
  # Retry settings
  max_retries: 3
  retry_delay_ms: 1000
  exponential_backoff: true
  
  # Fallback behavior
  enable_fallbacks: true
  graceful_degradation: true
  
  # Circuit breaker
  circuit_breaker:
    failure_threshold: 5
    recovery_timeout: 30

# Development and debugging
development:
  # Debug mode (disable in production)
  debug: false
  
  # API documentation
  enable_swagger: true
  swagger_ui_path: "/docs"
  
  # Metrics
  enable_metrics: true
  metrics_path: "/metrics"
